### ISSUE TITLE
TODO [New Features]

### ISSUE THREAD

**Issue by RomainBrault** [operalib/operalib#1]
- [ ] Remove .dat files (I think they are still in the deltas)
- [ ] Implement Lim et al. algorithms
- [ ] Implement IOKR
- [ ] Implement Semi-Supervised
- [x] Implement Quantile Regression
- [x] Implement ONORMA
