### ISSUE TITLE
TODO [Maintenance]

### ISSUE THREAD

**Issue by RomainBrault** [operalib/operalib#4]
- [ ] Refactor Quantile Regression
- [ ] Refactor Losses and Risk
- [ ] Refactor ORFF maps with kernels maps
- [x] Unit tests for  Quantile Regression

**Comment by RomainBrault** [comment]
Now passing check_estimator, and some unit tests (Quantile Regression)
